site_name: 'AWS Handson'

theme:
  name: 'material'
  language: 'ja'
  palette:
    primary: 'deep purple'
    accent: 'deep purple'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  highlightjs: true
  hljs_languages:
    - 'yaml'
    - 'dockerfile'
    - 'ruby'

extra:
  search:
    language: 'jp'

markdown_extensions:
  - 'admonition'
  - 'footnotes'
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.tasklist:
      custom_checkbox: true

extra_css:
  - 'assets/custom.css'

extra_javascript:
  - 'assets/custom.js'

nav:
  - 'Home': 'index.md'
  - 'Terraform':
    - '概要': 'terraform/about.md'
    - 'コマンドの用意': 'terraform/command.md'
    - 'ハンズオン': 'terraform/handson.md'
  - 'ECS':
    # - '概要': 'ecs/index.md'
    - 'ハンズオンの環境構築': 'ecs/provisioning.md'
    - 'docker-composeで動作確認をする': 'ecs/docker-compose.md'
    - 'LaravelをECSで動かす': 'ecs/laravel.md'
    - 'Auroraと連携': 'ecs/aurora.md'
  - 'Datadog':
    - '概要': 'datadog/index.md'
    - 'docker-composeで起動': 'datadog/docker-compose.md'
    - 'ECSとの連携': 'datadog/ecs.md'
    - 'AWSとの連携': 'datadog/aws.md'
